name: 01 - Hello
# El nombre del workflow que aparece en la interfaz de GitHub Actions.

on:
  # Define los eventos que disparan este workflow.
  push:
    # Cuando se hace push a las ramas listadas, se ejecuta el workflow.
    # Aquí indicamos que solo se ejecute al hacer push en la rama 'main'.
    # Puedes cambiar a otra rama o usar '*' para todas las ramas.
    branches: [main]

jobs:
  # Los jobs son las unidades de trabajo que se ejecutan en runners.
  hello:
    # Identificador del job. Puedes poner cualquier nombre descriptivo.

    # runs-on indica el sistema operativo del runner que ejecutará este job.
    # En este caso usamos una máquina virtual con Ubuntu 24.04.
    runs-on: ubuntu-24.04

    steps:
      # Cada step es una acción o un comando que se ejecuta en el runner.

      - name: Saludar
        # 'name' es una etiqueta para el step que se muestra en la UI.
        # 'run' ejecuta un comando en la shell del runner.
        run: echo "Hola Desde GitHub Actions!"

      - name: Ver fecha de runner
        # Este comando imprime la fecha y hora del runner.
        run: date

      - name: Ver archivos disponibles
        # Lista los archivos y carpetas presentes en el directorio de trabajo.
        # 'ls -la' muestra detalles como permisos, propietario y tamaño.
        run: ls -la

  repo-files:
    # Para recuperar los archivos del repositorio, se utiliza la acción 'actions/checkout'.
    # Esto es necesario para que los comandos posteriores puedan acceder a los archivos del proyecto.
    runs-on: ubuntu-24.04
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v6
        # Esta acción clona el repositorio en el runner, permitiendo que los siguientes steps accedan a los archivos del proyecto.
        
        # ====
        # with:
          # Aquí puedes configurar opciones adicionales para la acción 'actions/checkout'.
          # Por ejemplo, puedes especificar una rama, un token de autenticación, etc.
          # En este caso, no se están utilizando opciones adicionales.
          # repository: ${{ github.repository }}
          # 'repository' es una variable de entorno que contiene el nombre del repositorio en formato 'owner/repo'.
          # ref: main o repo
          # 'ref' especifica la rama o el commit que se desea descargar. Aquí se indica 'main', pero puedes cambiarlo según tus necesidades.
          # ====
          
      - name: Listar archivos del repositorio
        run: ls -la
        # Este comando muestra los archivos y carpetas del repositorio que se han descargado en el runner.
        
